### ISSUE TITLE
Making cleanup branch functional

### ISSUE THREAD

**Issue by muraliadithya** [eionblanc/mini-sygus#12]
The cleanup branch has all the necessary modules for creating a sygus solver. This needs to be combined with (i) reading a sygus file (ii) finding and replacing the synth-fun commands and then (iii) running the file using an SMT solver, getting valuations for boolean variables and finally (iv) using them to output a yield of the grammar satisfying the synthesis constraints.

**Comment by eionblanc** [comment]
A current example of full functionality is shown via the following terminal command:
`python3 -m src.engine 'data/out_sdlist-dlist-and-slist.sy'`
